customhost = "assignment.cjzspdft33rp.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "assignment"
custombucket = "leejiaxuan-bucket"
customregion = "us-east-1"